# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto.process import processor_pb2 as proto_dot_process_dot_processor__pb2


class ProcessorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessImage = channel.unary_unary(
        '/processor.Processor/ProcessImage',
        request_serializer=proto_dot_process_dot_processor__pb2.ProcessImageRequest.SerializeToString,
        response_deserializer=proto_dot_process_dot_processor__pb2.ProcessImageReply.FromString,
        )


class ProcessorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProcessImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessImage': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessImage,
          request_deserializer=proto_dot_process_dot_processor__pb2.ProcessImageRequest.FromString,
          response_serializer=proto_dot_process_dot_processor__pb2.ProcessImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'processor.Processor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
