FROM python:3.6-stretch AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main.py .
ADD proto ./proto

RUN wget -O grpc-health-probe -q https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.1/grpc_health_probe-linux-amd64 \
    && chmod +x grpc-health-probe

EXPOSE 50052
ENTRYPOINT ["python3", "main.py"]

