apiVersion: v1
kind: Service
metadata:
  name: api-service-external
  namespace: vml
  annotations:
      hetzner.external: "True"
spec:
  externalIPs: 
  - 78.47.84.126
  selector:
    app: api-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
