apiVersion: v1
kind: Service
metadata:
  name: image-processor
  namespace: vml
  labels:
    app: image-processor
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
  selector:
    app: image-processor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
  namespace: vml
  labels:
    app: image-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: image-processor 
          image: cytram/image-processor
          ports:
            - containerPort: 50052
          resources:
            requests:
              memory: 256Mi
              cpu: 1500m
            limits:
              memory: 768Mi
              cpu: 2000m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: image-processor
  namespace: vml
  labels:
    app: image-processor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processor
  minReplicas: 2
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
